- hosts: all
  become: yes
  tasks:

  - name: "Update system packages (Debian/Ubuntu)"
    apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true
    when: ansible_os_family == "Debian"

  - name: "Update system packages (RHEL/Fedora/CentOS)"
    dnf:
        update_cache: yes
        name: "*"
        state: latest
    when: ansible_os_family == "RedHat"

  - name: Install Required Packages
    package:
        name:
          - unzip
          - zip
          - curl
          - nano
        state: latest

# Some other examples of what you could do with ansible to customize your templates:
#
#  - name: Make sure we have a 'wheel' group
#    group:
#        name: wheel
#        state: present
#
#  - name: Allow 'wheel' group to have passwordless sudo
#    lineinfile:
#        dest: /etc/sudoers
#        state: present
#        regexp: '^%wheel'
#        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#        validate: 'visudo -cf %s'
#
#  - name: Create User Ansible
#    user:
#        name: "ansible"
#        state: present
#        createhome: yes
#        shell: /bin/bash
#
#  - name: Add SSH key to authorized_keys
#    authorized_key:
#        user: ansible
#        key: "{{ VM_PUBKEY }}"
#        state: present
#
#  - name: Add Ansible users to wheel group
#    user:
#        name: ansible
#        groups: wheel
#        append: yes
#        state: present
#
#  - name: "Create User {{ VM_USERNAME }}"
#    user:
#        name: "{{ VM_USERNAME }}"
#        state: present
#        createhome: yes
#        shell: /bin/bash
#        password: "{{ VM_PASSWORD }}"
#
#  - name: Add "{{ VM_USERNAME }}" users to sudo group
#    user:
#        name: "{{ VM_USERNAME }}"
#        groups: sudo
#        append: yes
#        state: present
#
#  - name: Add SSH key to authorized_keys
#    authorized_key:
#        user: "{{ VM_USERNAME }}"
#        key: "{{ VM_PUBKEY }}"
#        state: present
#
#  - name: Disable remote login for root
#    ansible.builtin.lineinfile:
#      path: /etc/ssh/sshd_config
#      state: present
#      regexp: '^PermitRootLogin yes'
#      line: 'PermitRootLogin no'
#
#  - name: Download MOTD files
#    get_url:
#        url: "{{ item }}"
#        dest: "/etc/update-motd.d/{{ item.split('/')[-1] }}"
#        mode: '0755'
#        owner: root
#        group: root
#    with_items: "{{ motd_urls }}"
#
#  - name: Ensure correct permissions for MOTD files
#    file:
#        path: "/etc/update-motd.d/{{ item.split('/')[-1] }}"
#        owner: root
#        group: root
#        mode: '0755'
#    with_items: "{{ motd_urls }}"
